DROP TABLE IF EXISTS spitter;

CREATE TABLE spitter (
  user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar not null,
  user_password varchar not null,
  user_full_name varchar not null,
  user_mail varchar,
  is_update_by_email boolean
);

CREATE INDEX idx_user_id ON spitter(user_id);
